env:
  global:
  - CC_TEST_REPORTER_ID=49bbac843bfe5aa24ae152ffdce27eec3aab51b7eda0dddd6a6eeb3889b17a8e

language: ruby

rvm:
- 2.4.0

sudo: false

install:
- bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}

# Setup the database
before_script: bundle exec rake db:create db:migrate db:seed

# Run the test suites
script:
- bundle exec rubocop -DESP           # Backend linting
- bundle exec rake                    # Backend specs

# Pipe the coverage data to Code Climate
after_script:
- ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
- ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
- if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json

before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after-build:
- bin/rake test test/controllers

cache:
  directories:
  - vendor/bundle

matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true